### ISSUE TITLE
(limit.map) RangeError: Maximum call stack size exceeded

### ISSUE THREAD

**Issue by SEAPUNK** [featurist/promise-limit#4]
I'm getting this error on calls to limit.map.

```js
export async function doThings () {
  active.length // 77199
  const limiter = promiseLimit(100)
  await limiter.map(active, i => processProduct(service, i, initialCache, shiprates))
}

async function processProduct () {
  // ...
}
```

```
    at remove (/home/ivan/code/xbpf3/services/invqtycost/node_modules/promise-limit/index.js:10:19)
    at run (/home/ivan/code/xbpf3/services/invqtycost/node_modules/promise-limit/index.js:51:7)
    at dequeue (/home/ivan/code/xbpf3/services/invqtycost/node_modules/promise-limit/index.js:23:7)
    at remove (/home/ivan/code/xbpf3/services/invqtycost/node_modules/promise-limit/index.js:14:7)
    at run (/home/ivan/code/xbpf3/services/invqtycost/node_modules/promise-limit/index.js:51:7)
    at dequeue (/home/ivan/code/xbpf3/services/invqtycost/node_modules/promise-limit/index.js:23:7)
    at remove (/home/ivan/code/xbpf3/services/invqtycost/node_modules/promise-limit/index.js:14:7)
    at run (/home/ivan/code/xbpf3/services/invqtycost/node_modules/promise-limit/index.js:51:7)
    at dequeue (/home/ivan/code/xbpf3/services/invqtycost/node_modules/promise-limit/index.js:23:7)
    at remove (/home/ivan/code/xbpf3/services/invqtycost/node_modules/promise-limit/index.js:14:7)
    at run (/home/ivan/code/xbpf3/services/invqtycost/node_modules/promise-limit/index.js:51:7)
    at dequeue (/home/ivan/code/xbpf3/services/invqtycost/node_modules/promise-limit/index.js:23:7)
    at remove (/home/ivan/code/xbpf3/services/invqtycost/node_modules/promise-limit/index.js:14:7)
    at run (/home/ivan/code/xbpf3/services/invqtycost/node_modules/promise-limit/index.js:51:7)
    at dequeue (/home/ivan/code/xbpf3/services/invqtycost/node_modules/promise-limit/index.js:23:7)
    at remove (/home/ivan/code/xbpf3/services/invqtycost/node_modules/promise-limit/index.js:14:7)
```

Not quite sure what's causing this. I'll investigate some more.

**Comment by SEAPUNK** [comment]
I'm running an isolated test, but it's not giving me the error. Weird, might be a bug with my code after all.

**Comment by SEAPUNK** [comment]
Okay, I know what's going on. It is a bug with my code, but a bug with yours as well.

Consider this code:

```js
import promiseLimit from 'promise-limit'

const ar = []

for (let i = 0; i < 70000; i++) {
  ar.push(i)
}

async function processThing (val) {
  console.log('doing thing', val)
  if (val === 400) {
    throw new Error('failing')
  }
  return val
}

async function doThings () {
  const limiter = promiseLimit(100)
  const retval = await limiter.map(ar, i => processThing(i))
  console.log('done', retval)
}

doThings().catch(err => console.log('an error happened', err.stack))
```

When the code fails at iteration 400, it max stacks failing the promise.

**Comment by SEAPUNK** [comment]
I'll open a PR to fix this in just a second.

**Comment by SEAPUNK** [comment]
PR/discussion: #5
